# Generated by Django 3.2.9 on 2021-11-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='publish_date',
            new_name='publish',
        ),
    ]
