# Generated by Django 3.2.9 on 2021-11-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_publish_date_blog_post_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_post',
            options={'ordering': ['-publish']},
        ),
        migrations.AddField(
            model_name='blog_post',
            name='category',
            field=models.CharField(choices=[('cat_1', ''), ('cat_2', 'Trading Systems'), ('cat_3', 'Finance'), ('cat_4', 'News'), ('cat_5', 'BlackBox'), ('cat_6', 'Forex'), ('cat_7', 'Crypto'), ('cat_8', 'Stocks')], default='cat_1', max_length=20),
        ),
    ]
