# Generated by Django 3.2.9 on 2021-11-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211110_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='category',
            field=models.CharField(choices=[('cat_1', ''), ('Trading Systems', 'Trading Systems'), ('Finance', 'Finance'), ('News', 'News'), ('BlackBox', 'BlackBox'), ('Forex', 'Forex'), ('Crypto', 'Crypto'), ('Stocks', 'Stocks')], default='cat_1', max_length=20),
        ),
    ]
