# Generated by Django 3.2.9 on 2021-11-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='blog_post',
            options={'ordering': ['-publish'], 'verbose_name': 'Blog Post'},
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='category',
            field=models.CharField(blank=True, default='Main', max_length=50),
        ),
    ]
