# Generated by Django 3.2.9 on 2021-11-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211114_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='category',
            field=models.ForeignKey(blank=True, default='Main', on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
