# Generated by Django 3.2.9 on 2021-11-14 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
