# Generated by Django 3.2.9 on 2021-11-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_tinymce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TinyMCE',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='slug',
            field=models.SlugField(max_length=255, unique_for_date='publish'),
        ),
    ]
