# Generated by Django 3.2.9 on 2021-11-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211114_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique_for_date='publish'),
        ),
    ]
