# Generated by Django 3.2.9 on 2021-11-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='image',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
