# Generated by Django 3.2.9 on 2021-11-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(max_length=10)),
                ('Qty', models.IntegerField(max_length=10, verbose_name='Shares')),
                ('Entry_Date', models.DateField()),
                ('Current_Price', models.FloatField()),
                ('Entry_Value', models.FloatField()),
                ('Current_Value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockTicker',
            fields=[
                ('Ticker', models.CharField(max_length=10)),
                ('Date', models.DateField(primary_key=True, serialize=False)),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Volume', models.IntegerField(max_length=20)),
            ],
            options={
                'ordering': ['Ticker'],
            },
        ),
    ]
