# Generated by Django 3.2.9 on 2021-11-15 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioTable',
            new_name='PortfolioStock',
        ),
        migrations.AlterModelOptions(
            name='portfoliostock',
            options={'ordering': ['Ticker']},
        ),
    ]
